#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run test

php vendor/networkrailbusinesssystems/badges/badges.php
git add .github/*.svg
git diff-index --quiet --cached HEAD || git commit -m "Updated badges" --no-verify
